export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

export const FETCH_SEARCH_CATEGORY_ID_REQUEST = 'FETCH_SEARCH_CATEGORY_ID_REQUEST';
export const FETCH_SEARCH_CATEGORY_ID_SUCCESS = 'FETCH_SEARCH_CATEGORY_ID_SUCCESS';
export const FETCH_SEARCH_CATEGORY_ID_FAILURE = 'FETCH_SEARCH_CATEGORY_ID_FAILURE';

export const FETCH_SEARCH_CATEGORY_REQUEST = 'FETCH_SEARCH_CATEGORY_REQUEST';
export const FETCH_SEARCH_CATEGORY_SUCCESS = 'FETCH_SEARCH_CATEGORY_SUCCESS';
export const FETCH_SEARCH_CATEGORY_FAILURE = 'FETCH_SEARCH_CATEGORY_FAILURE';